### ISSUE TITLE
Something wrong with jsitter lib

### ISSUE THREAD

**Issue by ghost** [ikws4/CodeEditor#2]
* What went wrong:
Execution failed for task ':jsitter:generateJsonModelDebug'.
> /home/runner/work/CodeEditor-2/CodeEditor-2/jsitter/src/main/cpp/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at /home/runner/work/CodeEditor-2/CodeEditor-2/jsitter/src/main/cpp/CMakeLists.txt:13 (add_library):
    Cannot find source file:
  grammars/tree-sitter-java/src/parser.c
  
Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
    .hxx .in .txx

**Comment by ikws4** [comment]
Did you tried `git clone --recursive https://github.com/ikws4/CodeEditor.git`?

It seems you don't clone the `tree-sitter-java` submodule.

**Comment by ghost** [comment]
> Did you tried `git clone --recursive https://github.com/ikws4/CodeEditor.git`?
> 
> It seems you don't clone the `tree-sitter-java` submodule.

I just fork it and build via github workflows:(

**Comment by ikws4** [comment]
Mabye you can add `submodules: 'true'` to see if it works.
Refer: [checkout-usage](https://github.com/actions/checkout#usage)

**Comment by ghost** [comment]
it's working thanks for your time dude
